image: kkarczmarczyk/node-yarn

stages:
  - production

before_script:
  - apt-get update
  - rm -rf node_modules
  # yarn
  - yarn
  - CI=false RAZZLE_ENDPOINT=https://server-pms.dwdev.site/api yarn build

  # ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_production:
   stage: production
   only:
     - master
   script:
     - ssh-add <(echo "$AWS_SSH_KEY")
     - ssh centos@3.0.122.222 "rm -rf /usr/share/nginx/html/projects/db_pms/client/*"
     - scp -r build/* centos@3.0.122.222:/usr/share/nginx/html/projects/db_pms/client/
     - scp package.json centos@3.0.122.222:/usr/share/nginx/html/projects/db_pms/client/
     - ssh centos@3.0.122.222 "cd /usr/share/nginx/html/projects/db_pms/client && yarn"
